
services:
  mongo:
    image: mongo:6
    container_name: ims-mongo
    ports:
      - "27017:27017"
    volumes:
      - ims_mongo_data:/data/db
    restart: unless-stopped

volumes:
  ims_mongo_data:
